const $=s=>document.querySelector(s),esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));let expedientes=[];
function toast(m,e=false){const t=$("#toast");t.textContent=m;t.style.background=e?"#8b2635":"#192f45";t.style.display="block";setTimeout(()=>t.style.display="none",4000)}
async function api(u,o={}){const r=await fetch(u,o),d=await r.json();if(!r.ok)throw new Error(d.error||"Error de operación");return d}
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll("nav button,.view").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("#"+b.dataset.view).classList.add("active");if(b.dataset.view==="auditoria")loadAudit()});
async function loadExp(){expedientes=await api("/api/expedientes");$("#exp-list").innerHTML=expedientes.map(e=>`<div class="item"><span class="meta">${esc(e.estado_procesal||"SIN ESTADO")}</span><h3>${esc(e.numero)}</h3><p>${esc(e.actor)} vs. ${esc(e.demandado)}</p><p>${esc(e.juzgado)} · ${esc(e.distrito_judicial)} · ${esc(e.ciudad)}</p><button data-edit="${e.id}">Editar</button></div>`).join("")||'<div class="item">No hay expedientes registrados.</div>';$("#gen-exp").innerHTML='<option value="">Seleccione…</option>'+expedientes.map(e=>`<option value="${e.id}">${esc(e.numero)} — ${esc(e.actor)}</option>`).join("");document.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>editExp(Number(b.dataset.edit)))}
function editExp(id){const e=expedientes.find(x=>x.id===id),f=$("#exp-form");Object.keys(e).forEach(k=>{if(f.elements[k])f.elements[k].value=e[k]??""});f.scrollIntoView({behavior:"smooth"})}
$("#nuevo").onclick=()=>$("#exp-form").reset();
$("#exp-form").onsubmit=async ev=>{ev.preventDefault();const f=ev.currentTarget,d=Object.fromEntries(new FormData(f)),id=d.id;delete d.id;try{await api(id?`/api/expedientes/${id}`:"/api/expedientes",{method:id?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(d)});f.reset();toast(id?"Expediente corregido y cambio auditado":"Expediente creado");await loadExp()}catch(e){toast(e.message,true)}};
async function loadTes(q=""){const rows=await api(`/api/tesauro?q=${encodeURIComponent(q)}`);$("#tes-list").innerHTML=rows.map(x=>`<div class="item"><span class="meta">${esc(x.clase.replaceAll("_"," ").toUpperCase())}</span><h3>${esc(x.titulo)}</h3><p>${esc(x.organo)} · ${esc(x.expediente_origen)} · ${esc(x.fecha_resolucion)}</p><p>Estado: ${esc(x.estado)} · Archivo: ${esc(x.archivo_nombre)}</p></div>`).join("")||'<div class="item">No se encontraron documentos.</div>'}
let timer;$("#tes-search").oninput=e=>{clearTimeout(timer);timer=setTimeout(()=>loadTes(e.target.value),250)};
$("#tes-form").onsubmit=async ev=>{ev.preventDefault();const f=ev.currentTarget;f.classList.add("loading");try{const r=await api("/api/tesauro",{method:"POST",body:new FormData(f)});toast(`Documento incorporado: ${r.caracteres.toLocaleString()} caracteres`);f.reset();await loadTes()}catch(e){toast(e.message,true)}finally{f.classList.remove("loading")}};
$("#gen-form").onsubmit=async ev=>{ev.preventDefault();const f=ev.currentTarget,d=Object.fromEntries(new FormData(f));f.classList.add("loading");$("#resultado").textContent="Analizando expediente y Tesauro…";try{const r=await api("/api/generaciones",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(d)});$("#resultado").textContent=r.resultado;toast(`Borrador generado con ${r.modelo}; ${r.fuentes.length} fuentes recuperadas`)}catch(e){$("#resultado").textContent="No fue posible generar el borrador.";toast(e.message,true)}finally{f.classList.remove("loading")}};
async function loadAudit(){const rows=await api("/api/auditoria");$("#audit-list").innerHTML=rows.map(x=>`<div class="item"><span class="meta">${esc(x.created_at)}</span><h3>${esc(x.accion)} · ${esc(x.entidad)} #${esc(x.entidad_id)}</h3><p>${esc(x.detalle)}</p></div>`).join("")||'<div class="item">Sin movimientos.</div>'}
try{const h=await api("/api/health");$("#health").textContent=h.aiConfigured?"Motor OpenAI listo":"Motor sin configurar";await Promise.all([loadExp(),loadTes()])}catch(e){toast(e.message,true)}
