import { backup as sqliteBackup } from "node:sqlite";
import crypto from "node:crypto";
import fs from "node:fs";
import fsp from "node:fs/promises";
import path from "node:path";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { pipeline } from "node:stream/promises";
import db from "./db.js";

const execFileAsync=promisify(execFile),root=path.resolve(".data/backups"),magic=Buffer.from("SIJOLBK1");
await fsp.mkdir(root,{recursive:true});
const safeName=name=>path.basename(name).replace(/[^a-zA-Z0-9._-]/g,"-");
async function sha(file){const hash=crypto.createHash("sha256");await pipeline(fs.createReadStream(file),hash);return hash.digest("hex");}
async function walk(dir,base=dir){const out=[];for(const entry of await fsp.readdir(dir,{withFileTypes:true}).catch(()=>[])){const full=path.join(dir,entry.name);if(entry.isDirectory())out.push(...await walk(full,base));else if(entry.isFile())out.push({file:full,path:path.relative(base,full)});}return out;}
async function encrypt(input,output,password){const salt=crypto.randomBytes(16),iv=crypto.randomBytes(12),key=crypto.scryptSync(password,salt,32),cipher=crypto.createCipheriv("aes-256-gcm",key,iv),target=fs.createWriteStream(output,{mode:0o600});target.write(Buffer.concat([magic,salt,iv]));await pipeline(fs.createReadStream(input),cipher,target,{end:false});await new Promise((resolve,reject)=>{target.end(cipher.getAuthTag(),resolve);target.on("error",reject);});}
async function decrypt(input,output,password){const stat=await fsp.stat(input);if(stat.size<52)throw new Error("El archivo no es un respaldo SIJ-OL válido");const fd=await fsp.open(input,"r");const head=Buffer.alloc(36),tag=Buffer.alloc(16);await fd.read(head,0,36,0);await fd.read(tag,0,16,stat.size-16);await fd.close();if(!head.subarray(0,8).equals(magic))throw new Error("Formato de respaldo no reconocido");const key=crypto.scryptSync(password,head.subarray(8,24),32),decipher=crypto.createDecipheriv("aes-256-gcm",key,head.subarray(24,36));decipher.setAuthTag(tag);try{await pipeline(fs.createReadStream(input,{start:36,end:stat.size-17}),decipher,fs.createWriteStream(output,{mode:0o600}));}catch{throw new Error("Contraseña incorrecta o respaldo alterado");}}
async function extractSafe(tar,stage){const {stdout:names}=await execFileAsync("tar",["-tzf",tar]);for(const name of names.split("\n").filter(Boolean)){const normalized=path.posix.normalize(name.replace(/^\.\//,""));if(path.posix.isAbsolute(name)||normalized===".."||normalized.startsWith("../"))throw new Error("El respaldo contiene rutas inseguras");}const {stdout:details}=await execFileAsync("tar",["-tvzf",tar]);for(const line of details.split("\n").filter(Boolean))if(!["-","d"].includes(line[0]))throw new Error("El respaldo contiene enlaces o elementos no permitidos");await execFileAsync("tar",["-xzf",tar,"--no-same-owner","--no-same-permissions","-C",stage]);}

export async function crearRespaldo(password,version){if(String(password).length<14)throw new Error("La contraseña del respaldo debe tener al menos 14 caracteres");const id=new Date().toISOString().replace(/[:.]/g,"-");const temp=await fsp.mkdtemp(path.join(root,"tmp-")),stage=path.join(temp,"contenido");await fsp.mkdir(stage);try{const sqlite=path.join(stage,"sijol.sqlite");await sqliteBackup(db,sqlite);const uploads=path.resolve("uploads");if(fs.existsSync(uploads))await fsp.cp(uploads,path.join(stage,"uploads"),{recursive:true});const files=await walk(stage);const manifest={format:1,created_at:new Date().toISOString(),app_version:version,files:[]};for(const item of files)manifest.files.push({path:item.path.replaceAll(path.sep,"/"),size:(await fsp.stat(item.file)).size,sha256:await sha(item.file)});await fsp.writeFile(path.join(stage,"manifest.json"),JSON.stringify(manifest,null,2));const tar=path.join(temp,"backup.tar.gz"),output=path.join(root,`SIJOL-${id}.sijolbak`);await execFileAsync("tar",["-czf",tar,"-C",stage,"."]);await encrypt(tar,output,password);return {nombre:path.basename(output),tamano:(await fsp.stat(output)).size,created_at:manifest.created_at,archivos:manifest.files.length};}finally{await fsp.rm(temp,{recursive:true,force:true});}}
export async function listarRespaldos(){const rows=[];for(const name of await fsp.readdir(root)){if(!name.endsWith(".sijolbak"))continue;const stat=await fsp.stat(path.join(root,name));rows.push({nombre:name,tamano:stat.size,created_at:stat.birthtime.toISOString()});}return rows.sort((a,b)=>b.created_at.localeCompare(a.created_at));}
export function rutaRespaldo(name){const safe=safeName(name);if(safe!==name||!safe.endsWith(".sijolbak"))return null;return path.join(root,safe);}
export async function verificarRespaldo(file,password){const temp=await fsp.mkdtemp(path.join(root,"verify-")),tar=path.join(temp,"backup.tar.gz"),stage=path.join(temp,"contenido");try{await decrypt(file,tar,password);await fsp.mkdir(stage);await extractSafe(tar,stage);const manifest=JSON.parse(await fsp.readFile(path.join(stage,"manifest.json"),"utf8"));for(const item of manifest.files){const candidate=path.resolve(stage,item.path);if(!candidate.startsWith(stage+path.sep)||await sha(candidate)!==item.sha256)throw new Error(`Integridad inválida: ${item.path}`);}return {valido:true,created_at:manifest.created_at,app_version:manifest.app_version,archivos:manifest.files.length};}finally{await fsp.rm(temp,{recursive:true,force:true});}}
export async function restaurarRespaldo(file,password,version){
  const temp=await fsp.mkdtemp(path.join(root,"restore-")),tar=path.join(temp,"backup.tar.gz"),stage=path.join(temp,"contenido");
  try{await decrypt(file,tar,password);await fsp.mkdir(stage);await extractSafe(tar,stage);const manifest=JSON.parse(await fsp.readFile(path.join(stage,"manifest.json"),"utf8"));for(const item of manifest.files){const candidate=path.resolve(stage,item.path);if(!candidate.startsWith(stage+path.sep)||await sha(candidate)!==item.sha256)throw new Error(`Integridad inválida: ${item.path}`);}await crearRespaldo(password,version);db.close();await fsp.copyFile(path.join(stage,"sijol.sqlite"),path.resolve(".data/sijol.sqlite"));const sourceUploads=path.join(stage,"uploads"),uploads=path.resolve("uploads");await fsp.rm(uploads,{recursive:true,force:true});if(fs.existsSync(sourceUploads))await fsp.cp(sourceUploads,uploads,{recursive:true});return {restaurado:true,created_at:manifest.created_at,archivos:manifest.files.length};}finally{await fsp.rm(temp,{recursive:true,force:true});}
}
