import db, { audit, now } from "./db.js";

const fechaSonora = date => Object.fromEntries(new Intl.DateTimeFormat("en",{timeZone:"America/Hermosillo",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(date).map(part=>[part.type,part.value]));
const claveFecha = date => {const p=fechaSonora(date);return `${p.year}-${p.month}-${p.day}`;};
const hoySonora = () => claveFecha(new Date());
const sumarDia = fecha => { const date=new Date(`${fecha}T12:00:00-07:00`);date.setDate(date.getDate()+1);return claveFecha(date); };
function semaforo(fecha,estado){if(estado!=="pendiente")return "gris";const hoy=hoySonora(),manana=sumarDia(hoy);if(!fecha||fecha>manana)return "verde";if(fecha===manana)return "amarillo";return "rojo";}
function enriquecer(row){return {...row,semaforo:semaforo(row.fecha_vencimiento,row.estado),aviso:!row.fecha_vencimiento?"Sin fecha":row.fecha_vencimiento<hoySonora()?"Vencida":row.fecha_vencimiento===hoySonora()?"Vence hoy":row.fecha_vencimiento===sumarDia(hoySonora())?"Vence mañana":"Próxima"};}

export function listarTareas(estado="pendiente",expedienteId=0) { const filtros=[],params=[];if(estado!=="todos")filtros.push("t.estado='pendiente'");if(Number(expedienteId)){filtros.push("t.expediente_id=?");params.push(Number(expedienteId));}const where=filtros.length?`WHERE ${filtros.join(" AND ")}`:"",rows=db.prepare(`SELECT t.*,e.numero expediente_numero,e.actor,e.demandado FROM tareas t LEFT JOIN expedientes e ON e.id=t.expediente_id ${where} ORDER BY CASE WHEN t.fecha_vencimiento='' THEN 1 ELSE 0 END,t.fecha_vencimiento,t.hora,t.id`).all(...params);return rows.map(enriquecer); }
export function avisosTareas(){const hoy=hoySonora(),manana=sumarDia(hoy);return listarTareas("pendiente").filter(row=>row.fecha_vencimiento&&row.fecha_vencimiento<=manana);}
export function crearTarea(datos){const t=now(),r=db.prepare("INSERT INTO tareas(expediente_id,agenda_id,origen,titulo,fecha_vencimiento,hora,prioridad,estado,notas,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)").run(datos.expediente_id||null,datos.agenda_id||null,datos.origen||"manual",String(datos.titulo||"").trim(),datos.fecha_vencimiento||"",datos.hora||"",datos.prioridad||"normal",datos.estado||"pendiente",datos.notas||"",t,t);audit("tarea",r.lastInsertRowid,"crear",datos);return enriquecer(db.prepare("SELECT * FROM tareas WHERE id=?").get(r.lastInsertRowid));}
export function actualizarTarea(id,datos){const anterior=db.prepare("SELECT * FROM tareas WHERE id=?").get(id);if(!anterior)return null;const titulo=String(datos.titulo??anterior.titulo).trim();if(!titulo)return null;const expedienteId=datos.expediente_id===""?null:(datos.expediente_id??anterior.expediente_id),fecha=String(datos.fecha_vencimiento??anterior.fecha_vencimiento??""),hora=String(datos.hora??anterior.hora??""),prioridad=["normal","alta","urgente"].includes(datos.prioridad)?datos.prioridad:anterior.prioridad,notas=String(datos.notas??anterior.notas??"");db.prepare("UPDATE tareas SET expediente_id=?,titulo=?,fecha_vencimiento=?,hora=?,prioridad=?,notas=?,updated_at=? WHERE id=?").run(expedienteId||null,titulo,fecha,hora,prioridad,notas,now(),id);const nueva=db.prepare("SELECT * FROM tareas WHERE id=?").get(id);audit("tarea",Number(id),"editar",{anterior:{expediente_id:anterior.expediente_id,titulo:anterior.titulo,fecha_vencimiento:anterior.fecha_vencimiento,hora:anterior.hora,prioridad:anterior.prioridad,notas:anterior.notas},nuevo:{expediente_id:nueva.expediente_id,titulo:nueva.titulo,fecha_vencimiento:nueva.fecha_vencimiento,hora:nueva.hora,prioridad:nueva.prioridad,notas:nueva.notas}});return enriquecer(nueva);}
export function crearDesdeAgenda(agendaId){const a=db.prepare("SELECT * FROM agenda WHERE id=?").get(agendaId);if(!a)return null;const existente=db.prepare("SELECT id FROM tareas WHERE agenda_id=?").get(agendaId);if(existente){db.prepare("UPDATE tareas SET expediente_id=?,titulo=?,fecha_vencimiento=?,hora=?,prioridad=?,estado=?,notas=?,updated_at=? WHERE id=?").run(a.expediente_id,a.titulo,a.fecha,a.hora,a.tipo==="termino"?"alta":"normal",a.estado,a.notas,now(),existente.id);return existente.id;}return crearTarea({expediente_id:a.expediente_id,agenda_id:a.id,origen:"agenda",titulo:a.titulo,fecha_vencimiento:a.fecha,hora:a.hora,prioridad:a.tipo==="termino"?"alta":"normal",estado:a.estado,notas:a.notas}).id;}
export function sincronizarEstadoAgenda(agendaId,estado){db.prepare("UPDATE tareas SET estado=?,updated_at=? WHERE agenda_id=?").run(estado,now(),agendaId);}
export function sincronizarEtapa(expedienteId,etapa,fecha){if(!String(etapa||"").trim()||!/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/.test(String(fecha||"")))return null;const existente=db.prepare("SELECT id FROM tareas WHERE expediente_id=? AND origen='etapa_procesal' AND estado='pendiente' ORDER BY id DESC LIMIT 1").get(expedienteId);const titulo=`Próxima etapa: ${String(etapa).trim()}`;if(existente){db.prepare("UPDATE tareas SET titulo=?,fecha_vencimiento=?,prioridad='alta',updated_at=? WHERE id=?").run(titulo,fecha,now(),existente.id);return existente.id;}return crearTarea({expediente_id:expedienteId,origen:"etapa_procesal",titulo,fecha_vencimiento:fecha,prioridad:"alta",notas:"Generada automáticamente desde la próxima etapa procesal"}).id;}
export function cambiarEstadoTarea(id,estado){if(!["pendiente","cumplido","cancelado"].includes(estado))return null;const tarea=db.prepare("SELECT * FROM tareas WHERE id=?").get(id);if(!tarea)return null;db.prepare("UPDATE tareas SET estado=?,updated_at=? WHERE id=?").run(estado,now(),id);if(tarea.agenda_id)db.prepare("UPDATE agenda SET estado=?,updated_at=? WHERE id=?").run(estado,now(),tarea.agenda_id);audit("tarea",Number(id),"cambiar_estado",{anterior:tarea.estado,nuevo:estado});return enriquecer(db.prepare("SELECT * FROM tareas WHERE id=?").get(id));}
